# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - delapp101

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_0eed2d03de2d4811bff9a18dfe3e483a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c778bcd2243c493e98c08974f4d22fbc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_0eed2d03de2d4811bff9a18dfe3e483a }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'delapp101'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e8eaf80df8c44d429b9115374c35727a }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_0eed2d03de2d4811bff9a18dfe3e483a }}/appsvc/staticsite:${{ github.sha }}'